services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: thalora-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TaloraDevPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P TaloraDevPassword123! -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: thalora-backend
    environment:
      - DATABASE_URL=Server=sqlserver,1433;Database=TaloraDB;User=sa;Password=TaloraDevPassword123!;TrustServerCertificate=true;
      - RUST_LOG=info
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sqlserver_data: